# Installed required libraries

# Import Libraries

In [20]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt

print('Libraries loaded.')

Libraries loaded.


# Loading dataset

In [21]:
file = open('Data/iris.txt', 'r')

data = file.read().split()

file.close()

print('Data loaded and the opened file stream has closed.')

Data loaded and the opened file stream has closed.


In [22]:
data

['5.9,3,4.2,1.5,"Iris-versicolor"',
 '6.9,3.1,4.9,1.5,"Iris-versicolor"',
 '6.6,2.9,4.6,1.3,"Iris-versicolor"',
 '4.6,3.2,1.4,0.2,"Iris-setosa"',
 '6,2.2,4,1,"Iris-versicolor"',
 '4.7,3.2,1.3,0.2,"Iris-setosa"',
 '6.5,3,5.8,2.2,"Iris-virginica"',
 '5.8,2.7,5.1,1.9,"Iris-virginica"',
 '6.7,3.1,5.6,2.4,"Iris-virginica"',
 '6.7,2.5,5.8,1.8,"Iris-virginica"',
 '5.1,3.7,1.5,0.4,"Iris-setosa"',
 '5.1,3.8,1.5,0.3,"Iris-setosa"',
 '5.7,3,4.2,1.2,"Iris-versicolor"',
 '6.1,3,4.9,1.8,"Iris-virginica"',
 '4.9,3.1,1.5,0.1,"Iris-setosa"',
 '5,3.4,1.6,0.4,"Iris-setosa"',
 '5,3.4,1.5,0.2,"Iris-setosa"',
 '5.7,2.8,4.1,1.3,"Iris-versicolor"',
 '5,3.3,1.4,0.2,"Iris-setosa"',
 '7.2,3.2,6,1.8,"Iris-virginica"',
 '5.9,3,5.1,1.8,"Iris-virginica"',
 '6.5,3,5.2,2,"Iris-virginica"',
 '5.7,4.4,1.5,0.4,"Iris-setosa"',
 '5.5,2.5,4,1.3,"Iris-versicolor"',
 '4.9,2.5,4.5,1.7,"Iris-virginica"',
 '5,3.5,1.6,0.6,"Iris-setosa"',
 '5.5,2.3,4,1.3,"Iris-versicolor"',
 '4.6,3.1,1.5,0.2,"Iris-setosa"',
 '7.2,3,5.8,1.6,"Iris-v

In [23]:
prepared_data = []

classes = []

vectorized_float = np.vectorize(float)

for line in data:
    
    l = line.split(',')
    
    prepared_data.append(vectorized_float(l[0: 4]))
    
    classes.append(l[-1][1:-1])
###   
    
prepared_data   

[array([5.9, 3. , 4.2, 1.5]),
 array([6.9, 3.1, 4.9, 1.5]),
 array([6.6, 2.9, 4.6, 1.3]),
 array([4.6, 3.2, 1.4, 0.2]),
 array([6. , 2.2, 4. , 1. ]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([6.5, 3. , 5.8, 2.2]),
 array([5.8, 2.7, 5.1, 1.9]),
 array([6.7, 3.1, 5.6, 2.4]),
 array([6.7, 2.5, 5.8, 1.8]),
 array([5.1, 3.7, 1.5, 0.4]),
 array([5.1, 3.8, 1.5, 0.3]),
 array([5.7, 3. , 4.2, 1.2]),
 array([6.1, 3. , 4.9, 1.8]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5. , 3.4, 1.5, 0.2]),
 array([5.7, 2.8, 4.1, 1.3]),
 array([5. , 3.3, 1.4, 0.2]),
 array([7.2, 3.2, 6. , 1.8]),
 array([5.9, 3. , 5.1, 1.8]),
 array([6.5, 3. , 5.2, 2. ]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.5, 2.5, 4. , 1.3]),
 array([4.9, 2.5, 4.5, 1.7]),
 array([5. , 3.5, 1.6, 0.6]),
 array([5.5, 2.3, 4. , 1.3]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([7.2, 3. , 5.8, 1.6]),
 array([6.8, 3.2, 5.9, 2.3]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5. , 3.2, 1.2, 0.2]),
 array([5.7, 2.5, 5. , 2. ]),
 array([5.

# Creating a dateframe

In [24]:
dataset = pd.DataFrame(prepared_data, 
                       columns= ['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

dataset['class'] = classes

dataset.head()

sepal_length  sepal_width  petal_length  petal_width            class
0           5.9          3.0           4.2          1.5  Iris-versicolor
1           6.9          3.1           4.9          1.5  Iris-versicolor
2           6.6          2.9           4.6          1.3  Iris-versicolor
3           4.6          3.2           1.4          0.2      Iris-setosa
4           6.0          2.2           4.0          1.0  Iris-versicolor

In [25]:
type(dataset)

pandas.core.frame.DataFrame

In [26]:
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# The best way for reading files into dataframes

In [27]:
df_iris = pd.read_csv('Data/iris.txt', sep= ',', header= None) 

df_iris.head()

0    1    2    3                4
0  5.9  3.0  4.2  1.5  Iris-versicolor
1  6.9  3.1  4.9  1.5  Iris-versicolor
2  6.6  2.9  4.6  1.3  Iris-versicolor
3  4.6  3.2  1.4  0.2      Iris-setosa
4  6.0  2.2  4.0  1.0  Iris-versicolor

In [28]:
df_iris.dtypes

0    float64
1    float64
2    float64
3    float64
4     object
dtype: object

# Preprocessing

In [29]:
df_iris.columns= ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'iris_name']

df_iris.head()

sepal_length  sepal_width  petal_length  petal_width        iris_name
0           5.9          3.0           4.2          1.5  Iris-versicolor
1           6.9          3.1           4.9          1.5  Iris-versicolor
2           6.6          2.9           4.6          1.3  Iris-versicolor
3           4.6          3.2           1.4          0.2      Iris-setosa
4           6.0          2.2           4.0          1.0  Iris-versicolor

In [30]:
encoder = LabelEncoder()

classes = encoder.fit_transform(df_iris['iris_name'])

df_iris['class'] = classes

df_iris

sepal_length  sepal_width  petal_length  petal_width        iris_name  \
0             5.9          3.0           4.2          1.5  Iris-versicolor   
1             6.9          3.1           4.9          1.5  Iris-versicolor   
2             6.6          2.9           4.6          1.3  Iris-versicolor   
3             4.6          3.2           1.4          0.2      Iris-setosa   
4             6.0          2.2           4.0          1.0  Iris-versicolor   
..            ...          ...           ...          ...              ...   
145           5.4          3.4           1.7          0.2      Iris-setosa   
146           5.5          2.6           4.4          1.2  Iris-versicolor   
147           6.7          3.0           5.2          2.3   Iris-virginica   
148           7.7          3.8           6.7          2.2   Iris-virginica   
149           5.1          3.4           1.5          0.2      Iris-setosa   

     class  
0        1  
1        1  
2        1  
3        0  
4        1  
..     ...  
145      0  
146      1  
147      2  
148      2  
149      0  

[150 rows x 6 columns]

In [31]:
dataset = df_iris.drop('iris_name', axis= 1)

dataset.head()

sepal_length  sepal_width  petal_length  petal_width  class
0           5.9          3.0           4.2          1.5      1
1           6.9          3.1           4.9          1.5      1
2           6.6          2.9           4.6          1.3      1
3           4.6          3.2           1.4          0.2      0
4           6.0          2.2           4.0          1.0      1

# Exploration

In [32]:
dataset.groupby(['class']).mean()

sepal_length  sepal_width  petal_length  petal_width
class                                                      
0             5.006        3.418         1.464        0.244
1             5.936        2.770         4.260        1.326
2             6.588        2.974         5.552        2.026

In [33]:
dataset.loc[0]

sepal_length    5.9
sepal_width     3.0
petal_length    4.2
petal_width     1.5
class           1.0
Name: 0, dtype: float64

In [34]:
dataset.loc[1]

sepal_length    6.9
sepal_width     3.1
petal_length    4.9
petal_width     1.5
class           1.0
Name: 1, dtype: float64

In [35]:
np.dot(dataset.loc[0], dataset.loc[1])

73.84

In [36]:
kernel = np.zeros((len(dataset), len(dataset)))

In [37]:
kernel[1, 1]= np.round(np.dot(dataset.loc[1], dataset.loc[1]), 3)

kernel[1, 1]

84.48

In [38]:
for i in range(0, len(dataset)):
    for j in range(i, len(dataset)):
        kernel[i,j]= np.round(np.dot(dataset.loc[i], dataset.loc[j]), 3)
k = pd.DataFrame(kernel)
k

0      1      2      3      4      5      6      7      8      9    ...  \
0    64.7  73.84  69.91  42.92  61.30  43.09  77.01  68.59  77.95  76.09  ...   
1     0.0  84.48  80.02  48.82  70.32  49.02  87.87  78.23  88.88  87.10  ...   
2     0.0   0.00  75.82  46.34  66.68  46.54  83.14  74.04  84.09  82.49  ...   
3     0.0   0.00   0.00  33.40  40.44  33.72  48.06  42.84  49.06  47.30  ...   
4     0.0   0.00   0.00   0.00  58.84  40.64  73.00  65.04  73.82  72.70  ...   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
145   0.0   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00  ...   
146   0.0   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00  ...   
147   0.0   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00  ...   
148   0.0   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00  ...   
149   0.0   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00  ...   

       140    141    142    143    144    145    146    147     148    149  
0    84.65  76.88  66.29  69.32  69.26  49.50  61.53  75.82   90.27  46.89  
1    96.48  87.66  75.79  79.32  78.92  56.43  70.37  86.46  103.04  53.38  
2    91.27  82.98  71.80  75.13  74.72  53.58  66.64  81.83   97.52  50.68  
3    53.68  49.26  44.08  45.60  44.28  38.14  40.02  48.16   57.40  36.48  
4    80.02  72.92  63.08  66.06  65.60  46.88  58.52  71.90   85.56  44.28  
..     ...    ...    ...    ...    ...    ...    ...    ...     ...    ...  
145   0.00   0.00   0.00   0.00   0.00  43.65  46.26  55.68   66.33  41.69  
146   0.00   0.00   0.00   0.00   0.00   0.00  58.81  72.29   86.35  43.73  
147   0.00   0.00   0.00   0.00   0.00   0.00   0.00  90.22  106.89  52.63  
148   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00  127.46  62.68  
149   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00    0.00  39.86  

[150 rows x 150 columns]